project:
  output-dir: docs
  type: book

book:
  title: "OMGN_USA"
  author: "Norah Jones"
  date: "2024. 9. 6."
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - economy.qmd
    - health.qmd 
    - demographics.qmd
    - car.qmd
    - smoke.qmd 
    - media.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



